### ISSUE TITLE
Default ini file opened is on lib dir

### ISSUE THREAD

**Issue by thisago** [juancarlospaco/nim-nimterlingua#3]
The opened `translations.cfg` file is opened in lib folder, not on project folder.

This makes mandatory the definition of `iniFile` path in compilation

**Comment by thisago** [comment]
Replacing the `iniFile` definition with below line, opens the `translations.cfg` file in same path of the project's main file
```nim
const iniFile {.strdefine.} = getProjectPath() & "/translations.cfg"
```

**Comment by juancarlospaco** [comment]
Yes you have to define the path at compilation, because **it works at compilation only**. 😄

I do not understand whats the bug if any...

**Comment by thisago** [comment]
Thanks for the fast answer!

Its not a bug, just a annoying, because I need to define the full path every time.
when I need to build in another PC, the path changes.

**Comment by thisago** [comment]
I created a `config.nims` with
```nim
switch("define", "iniFile=" & getCurrentDir() & "/translations.cfg")
```
and it solved.

**Comment by juancarlospaco** [comment]
If you propose a new default value for the location of the INI, 
feel free to send pull request, I will merge it, but user can just pass a path anyway.
